server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart-ai

langchain4j:
  open-ai:
    chat-model:
      # base-url: https://api.deepseek.com/v1
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      # api-key: ${DEEPSEEK_API_KEY}
      api-key: ${ALIBL_API_KEY}
      # model-name: deepseek-chat
      model-name: deepseek-r1
      log-requests: true
      log-responses: true

  ollama:
    chat-model:
      base-url: http://127.0.0.1:11434
      model-name: deepseek-r1:1.5b
      temperature: 0.8
      timeout: PT60S

  community:
    dashscope:
      chat-model:
        api-key: ${ALIBL_API_KEY}
        model-name: qwen-max
#logging:
#  level:
#    root: debug