server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart-ai
  datasource:
    url: jdbc:mysql://localhost:3306/huaxiaotuo?characterEncoding=utf-8&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

langchain4j:
  open-ai:
    chat-model:
      # base-url: https://api.deepseek.com/v1
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      # api-key: ${DEEPSEEK_API_KEY}
      api-key: ${ALIBL_API_KEY}
      # model-name: deepseek-chat
      model-name: deepseek-r1
      log-requests: true
      log-responses: true

  ollama:
    chat-model:
      base-url: http://127.0.0.1:11434
      model-name: deepseek-r1:1.5b
      temperature: 0.8
      timeout: PT60S

  community:
    dashscope:
      chat-model:
        api-key: ${ALIBL_API_KEY}
        model-name: qwen-max
#logging:
#  level:
#    root: debug